[package]
name = "lsrs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
colored = "3.0.0"
mime_guess = "2.0.5"
chrono = "0.4"
time = { version = "0.3", features = ["macros","local-offset"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
